### ISSUE TITLE
robertdebock.openssl : create PKCS task is failing 

### ISSUE THREAD

**Issue by theodore86** [robertdebock/ansible-role-openssl#2]
## Describe the bug

Hi,

I have encounter an execution error while executing for the **second time** the task: 

**TASK [robertdebock.openssl : create PKCS#12 file]** from **the ansible-role-openssl**.

It seems that something is going wrong with the underlying ansible module, If i completely (manual) **remove the PCKS file from the remote host**, the role is working fine.

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: 'Import python-pip role'
  ansible.builtin.import_role:
      name: 'robertdebock.python_pip'
  vars:
      python_pip_packages: '{{ hvault_python_pip_packages }}'
      python_pip_executable: '{{ hvault_python_pip_executable }}'
      python_pip_modules: '{{ hvault_python_pip_modules }}'

- name: 'Import openssl role'
  ansible.builtin.import_role:
      name: 'robertdebock.openssl'
  vars:
      openssl_items: '{{ hvault_tls_items }}'
      openssl_file_owner: '{{ hvault_user }}'
      openssl_file_group: '{{ hvault_group }}'
      openssl_key_directory: '{{ hvault_tls_key_directory }}'
      openssl_csr_directory: '{{ hvault_tls_csr_directory }}'
      openssl_crt_directory: '{{ hvault_tls_crt_directory }}'
```

Where:

```yaml
hvault_python_pip_packages:
  - 'python3-pip'
hvault_python_pip_executable: 'pip3'
hvault_python_pip_modules:
  - name: 'pyOpenSSL'
    state: 'present'
    version: '21.0.0'
```

## Output

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'builtins.Certificate' object has no attribute '_backend'
fatal: [hvault-1]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDOUT:

Traceback (most recent call last):
  File "/tmp/ansible-tmp-1637052380.924625-6731-228829550246404/AnsiballZ_openssl_pkcs12.py", line 100, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1637052380.924625-6731-228829550246404/AnsiballZ_openssl_pkcs12.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1637052380.924625-6731-228829550246404/AnsiballZ_openssl_pkcs12.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.crypto.plugins.modules.openssl_pkcs12', init_globals=dict(_module_fqn='ansible_collections.community.crypto.plugins.modules.openssl_pkcs12', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_pkcs12.py", line 762, in <module>
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_pkcs12.py", line 719, in main
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_pkcs12.py", line 397, in check
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_pkcs12.py", line 474, in parse
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/modules/openssl_pkcs12.py", line 587, in parse_bytes
  File "/tmp/ansible_community.crypto.openssl_pkcs12_payload_yl3zyb7q/ansible_community.crypto.openssl_pkcs12_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/cryptography_support.py", line 453, in parse_pkcs12
AttributeError: 'builtins.Certificate' object has no attribute '_backend'
```

## Environment

- Control node OS: Ubuntu 20.04 LTS
- Control node Ansible version: 4.5.0
- Managed node OS: Ubuntu 20.04 LTS

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by theodore86** [comment]
It seems that this issue has been fixed with the release of ansible 4.7.0
